"""Create initial tables

Revision ID: 1b48ca9aa283
Revises: 82c8da598dc9
Create Date: 2025-10-11 02:08:52.669021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b48ca9aa283'
down_revision: Union[str, None] = '82c8da598dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_hi', sa.String(length=255), nullable=True),
    sa.Column('name_gu', sa.String(length=255), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_hi', sa.Text(), nullable=True),
    sa.Column('description_gu', sa.Text(), nullable=True),
    sa.Column('eligibility_en', sa.Text(), nullable=True),
    sa.Column('eligibility_hi', sa.Text(), nullable=True),
    sa.Column('eligibility_gu', sa.Text(), nullable=True),
    sa.Column('benefits_en', sa.Text(), nullable=True),
    sa.Column('benefits_hi', sa.Text(), nullable=True),
    sa.Column('benefits_gu', sa.Text(), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('scheme_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemes_id'), 'schemes', ['id'], unique=False)
    op.create_table('tips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_hi', sa.String(length=255), nullable=True),
    sa.Column('title_gu', sa.String(length=255), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_hi', sa.Text(), nullable=True),
    sa.Column('description_gu', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('content_hi', sa.Text(), nullable=True),
    sa.Column('content_gu', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tip_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tips_id'), 'tips', ['id'], unique=False)
    op.create_table('weather_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('message_en', sa.Text(), nullable=False),
    sa.Column('message_hi', sa.Text(), nullable=True),
    sa.Column('message_gu', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('weather_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_alerts_id'), 'weather_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_weather_alerts_location'), 'weather_alerts', ['location'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_weather_alerts_location'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_id'), table_name='weather_alerts')
    op.drop_table('weather_alerts')
    op.drop_index(op.f('ix_tips_id'), table_name='tips')
    op.drop_table('tips')
    op.drop_index(op.f('ix_schemes_id'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
